# Nylo - Micro-framework for Flutter.
#
# Website: https://nylo.dev
# Official repository: https://github.com/nylo-core/nylo
# Author: Anthony Gordon <https://github.com/agordn52>

name: flutter_app
description: A new Nylo Flutter application.

publish_to: 'none'

version: 1.0.3+4

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.24.0 <4.0.0"
dependencies:
  url_launcher: ^6.2.6
  google_fonts: ^6.2.1
  analyzer: ^6.7.0
  intl: ^0.20.2
  nylo_framework: ^6.8.7
  pretty_dio_logger: ^1.4.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.4
  flutter_local_notifications: ^19.1.0
  font_awesome_flutter: ^10.8.0
  scaffold_ui: ^1.2.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.1.2
  flutter_svg: ^2.2.0
  table_calendar: ^3.2.0
  flutter_stripe: ^11.5.0
  flutter_tawk: ^0.1.0
  add_2_calendar: ^3.0.1
  sign_in_with_apple: ^7.0.1
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  google_sign_in: 6.1.5

  

dev_dependencies:
  rename: ^3.1.0
  flutter_launcher_icons: ^0.14.3
  # The following line 'flutter_lints' activates a set of recommended lints for Flutter apps,
  # packages, and plugins designed to encourage good coding practices.
#  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# APP ICON - public/app_icon/icon.png
# Build icons: "dart run flutter_launcher_icons"
flutter_launcher_icons:
  android: true
  # ios: true
  image_path: "public/app_icon/icon.png"
  remove_alpha_ios: true
  ios:
    generate: true
    image_path: "public/app_icon/icon.png"
    remove_alpha: true

# RENAME YOUR PROJECT
# flutter pub run rename setAppName --targets ios,android --value "YourAppName"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - public/fonts/
    - public/images/
    - public/app_icon/
    - lang/
    - .env
