# Nylo - Micro-framework for Flutter.
#
# Website: https://nylo.dev
# Official repository: https://github.com/nylo-core/nylo
# Author: Anthony Gordon <https://github.com/agordn52>

name: flutter_app
description: A new Nylo Flutter application.

publish_to: 'none'

version: 1.0.10+30

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.24.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  nylo_framework: ^6.8.7
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  url_launcher: ^6.2.6
  flutter_tawk: ^0.1.0
  table_calendar: ^3.2.0
  intl: ^0.20.2
  flutter_stripe: ^12.0.2
  pretty_dio_logger: ^1.4.0
  country_picker: ^2.0.25
  flutter_svg: ^2.0.9
  firebase_core: ^4.1.1
  firebase_storage: ^13.0.2
  firebase_analytics: ^12.0.2
  firebase_messaging: ^16.0.2
  sign_in_with_apple: ^7.0.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  # google_sign_in: ^6.1.5
  # sign_in_with_apple: ^7.0.1
  pin_code_fields: ^8.0.1
  add_2_calendar: ^3.0.1

  

dev_dependencies:
  rename: ^3.1.0
  flutter_launcher_icons: ^0.14.3
  # The following line 'flutter_lints' activates a set of recommended lints for Flutter apps,
  # packages, and plugins designed to encourage good coding practices.
#  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# APP ICON - public/app_icon/icon.png
# Build icons: "dart run flutter_launcher_icons"
flutter_launcher_icons:
  android: true
  # ios: true
  image_path: "public/app_icon/icon.png"
  remove_alpha_ios: true
  ios:
    generate: true
    image_path: "public/app_icon/icon.png"
    remove_alpha: true

# RENAME YOUR PROJECT
# flutter pub run rename setAppName --targets ios,android --value "YourAppName"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - public/fonts/
    - public/images/
    - public/app_icon/
    - lang/
    - .env
